GPUS: "0"
WORKERS: 2
OUTPUT: "output"

CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

DATASET: 
  NAME: "exam2"
  TRAIN: "datasets/exam_pose_classification_ds2/train"
  VAL: "datasets/exam_pose_classification_ds2/val"
  CHANNELS: 2
  JOINTS: 13
  NUM_CLASSES: 4

MODEL:
  NAME: "fc_net"

TRAIN:
  EPOCHS: 40
  EARLY_STOPPING:
  LR: 0.005
  LR_FACTOR: 0.1
  LR_STEP:
  - 20
  - 30
  BATCH_SIZE: 16
  WEIGHTS: ''
  OPTIMIZER: "adam"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  FLIP: 0.5
  RANDOM_SCORE: 0.05
  SHUFFLE: true

TEST:
  BATCH_SIZE: 32
  WEIGHTS: 'weights/fc_net_2_channels_exam2.pth'
  SHUFFLE: true
